# version: "3.8"

services:
  api:
    build: 
      context: dockerfiles
    container_name: api
    volumes:
      - ./:/var/www/html
    depends_on:
      - postgres
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: ${POSTGRES_PORT}
      DB_DATABASE: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
    networks:
      - tasks-net

  webserver:
    image: nginx:alpine
    container_name: webserver-tasks
    volumes:
      - ./:/var/www/html
      - ./dockerfiles/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
    ports:
      - "80:80"
    networks:
      - tasks-net

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./dockerfiles/data/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    networks:
      - tasks-net
      
volumes:
  pgdata:

networks:
  tasks-net:
    name: tasks-net